</head>
<body>
<h2 style="padding-top: 0px; width: 100%;"><b>Gesti&oacute;n Planillas Salariales</b></h2>
<div id='divTabPlanillasSal'>
<ul>
    <li id="liList">Listado</li>
    <li id="liNew">Generaci&oacute;n</li>
    <li id="liView">Vista</li>
</ul>
<br>
<div class="row section" id="divList">
    <div class="col-md-10">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Listado General</h2>
                <!--<select class="selectpicker" multiple data-max-options="2" data-live-search="true">
                    <option>Mustard</option>
                    <option>Ketchup</option>
                    <option>Relish</option>
                </select>-->

                <div id='divWidgetPlanillas'>
                    <div align="right">
                        <!--<button class="btn btn-sm btn-primary" type="button" id="btnExportarExcel" accesskey="i">
                            <i class="fi fi-xls"></i>
                            Exportar Excel
                        </button>
                        <button class="btn btn-sm btn-primary" type="button" id="btnExportarPDF" accesskey="i">
                            <i class="fi fi-pdf"></i>
                            Exportar PDF
                        </button>-->
                        <button class="btn btn-sm btn-primary" type="button" id="btnDesagrupartodo">
                            <i class="fa fa-chain-broken"></i>
                            Desagrupar Todo
                        </button>
                        <button class="btn btn-sm btn-primary" type="button" id="btnDesfiltrartodo">
                            <i class="gi gi-sorting"></i>
                            Desfiltrar Todo
                        </button>
                    </div>
                    <div id="divGridPlanillasSal"></div>
                </div>
            </div>
            <!-- END Input Grid Title -->

        </div>
        <!-- END Input Grid Block -->
    </div>
    <div class="col-md-2">
        <div class="block">
            <div class="block-title">
                <h2>Mostrar</h2>
                <br>
                <input type="checkbox" id="chkAllCols"> Todas / Ninguna
            </div>
            <div id="listBoxPlanillasSal"></div>
        </div>
    </div>
</div>
<div class="section" id="divGen">
    <div class="col-md-10">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Generaci&oacute;n de Planillas Salariales</h2>
                <div id='divWidgetPlanillasSal'>
                    <div class="row">
                        <div class="col-sm-2" id="divGestionGen">
                            <div class="block">Gesti&oacute;n:
                                <select class="form-control" id="lstGestionGen"><option value="">Seleccionar...</option></select>
                            </div>
                            <span class="help-block" id="helpErrorGestionGen"></span>
                        </div>
                        <div class="col-sm-2" id="divMesGen">
                            <div class="block">Mes:
                                <select id="lstMesGen" class="form-control"><option value="">Seleccionar...</option></select>
                            </div>
                            <span class="help-block" id="helpErrorMesGen"></span>
                        </div>
                        <div class="col-sm-6" id="divFinPartidaGen">
                            <div class="block">Fuente:
                                <select id="lstFinPartidaGen" class="form-control"><option value="">Seleccionar...</option></select>
                            </div>
                            <span class="help-block" id="helpErrorFinPartidaGen"></span>
                        </div>
                        <div class="col-sm-2" id="divTipoPlanillaSalGen">
                            <div class="block">Tipo:
                                <select id="lstTipoPlanillaSalGen" class="form-control"><option value="">Seleccionar...</option></select>
                            </div>
                            <span class="help-block" id="helpErrorTipoPlanillaSalGen"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <button class="btn btn-sm btn-primary" type="button" id="btnGenerarPlanillaPreviaSal" accesskey="d">
                                <i class="gi gi-search"></i>
                                Buscar
                            </button>
                            <button class="btn btn-sm btn-primary" type="button" id="btnCalcularPlanillaPreviaSal" accesskey="d">
                                <i class="gi gi-calculator"></i>
                                Calcular
                            </button>
                            <button class="btn btn-sm btn-primary" type="button" id="btnGenerarPlanillaSal" accesskey="g">
                                <i class="hi hi-cog"></i>
                                Generar
                            </button>
                            <button class="btn btn-sm btn-primary" type="button" id="btnDesfiltrarTodoPlanillasSalGen">
                                <i class="gi gi-sorting"></i>
                                Desfiltrar Todo
                            </button>
                        </div>
                    </div>
                    <div id="divCarga" style="display:none" align="center">
                        <div id="divContador"></div>
                        <img src="../images/barra_carga.gif" />
                    </div>
                    <div id="divGridPlanillasSalGen"></div>
                    <div id="divBotonesExportacion">
                    <button class="btn btn-sm btn-primary" type="button" id="btnExportarGenExcel" accesskey="i">
                        <i class="fi fi-xls"></i>
                        Exportar Excel
                    </button>
                    </div>
                    <input type="hidden" id="hdnSwPlanillaSalCalculada" value="0">
                </div>
            </div>
            <!-- END Input Grid Title -->

        </div>
        <!-- END Input Grid Block -->
    </div>
    <div class="col-md-2">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Mostrar</h2>
                <br>
                <!--<input type="checkbox" id="chkAllCols"> Todas / Ninguna-->

                <!--<div id="hintWrapper">
                    <div id="hintSection" class="hint">
                    </div>
                </div>-->
            </div>
            <div id="divPlanilllaSalGenListBox"></div>
            <!-- END Input Grid Title -->
        </div>
        <!-- END Input Grid Block -->
    </div>
</div>
<div class="section" id="divView">
    <div class="col-md-10">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Planillas Salariales Generadas</h2>
                <div id='divWidgetPlanillasSalView'>
                    <div id='divWidgetPlanillas'>
                        <div align="right">
                            <button class="btn btn-sm btn-primary" type="button" id="btnExportarViewExcel" accesskey="i">
                                <i class="fi fi-xls"></i>
                                Exportar Excel
                            </button>
                            <button class="btn btn-sm btn-primary" type="button" id="btnExportarViewPDF" accesskey="i">
                                <i class="fi fi-pdf"></i>
                                Exportar PDF
                            </button>
                            <button class="btn btn-sm btn-primary" type="button" id="btnDesagruparTodoPlanillasSalView">
                                <i class="fa fa-chain-broken"></i>
                                Desagrupar Todo
                            </button>
                            <button class="btn btn-sm btn-primary" type="button" id="btnDesfiltrarTodoPlanillasSalView">
                                <i class="gi gi-sorting"></i>
                                Desfiltrar Todo
                            </button>
                        </div>
                        <div class="block">
                            <div class="table-responsive">
                                <table id="tblDatosPlanillaSal" class="table table-vcenter table-striped">
                                    <thead>
                                    <tr>
                                        <th style='text-align: center'>Estado</th>
                                        <th style='text-align: center'>Gesti&oacute;n</th>
                                        <th style='text-align: center'>Mes</th>
                                        <th style='text-align: center'>Fuente</th>
                                        <th style='text-align: center'>Tipo / N&uacute;mero</th>
                                        <th style='text-align: center'>Observaci&oacute;n</th>
                                    </tr>
                                    </thead>
                                    <tbody id="tbodyDatosPlanillaSal"></tbody>
                                </table>
                            </div>
                        </div>
                        <div id="divGridPlanillasSalView"></div>
                        <input type="hidden" value="0" id="hdnIdPlanillaSal">
                    </div>
                </div>
            </div>
            <!-- END Input Grid Title -->

        </div>
        <!-- END Input Grid Block -->
    </div>
    <div class="col-md-2">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Mostrar</h2>
                <br>
                <!--<input type="checkbox" id="chkAllCols"> Todas / Ninguna-->

                <!--<div id="hintWrapper">
                    <div id="hintSection" class="hint">
                    </div>
                </div>-->
            </div>
            <div id="divPlanilllaSalViewListBox"></div>
            <!-- END Input Grid Title -->
        </div>
        <!-- END Input Grid Block -->
    </div>
</div>
</div>
<div class="modal fade bs-example-modal-lg" id="popupObservacionPlanillaSal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="form-horizontal" id="formObservacionPlanillaSal" data-toggle="validator" onsubmit="return false;"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <h4 class="modal-title" id="h4ModalObservacionPlanillaSal">Observaciones sobre la Planilla Salarial</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <div class="div-observacion-planillasal" id="divObservacionPlanillaSal">
                        <label class="col-sm-2 control-label" for="txtObservacionPlanillaSal">Observaci&oacute;n:</label>
                        <div class="col-md-10"  form-group>
                            <textarea id="txtObservacionPlanillaSal" class="form-control"></textarea>
                            <span class="help-block" id="helpErrorObservacionPlanillaSal"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnCerrarObservacionPlanillaSal" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-compress"></i>Cerrar</button>
                <button type="button" id="btnAplicarObservacionPlanillaSal" class="btn btn-primary"><i class="fa fa-thumbs-o-up"></i>Aplicar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-lg" id="popupObservacionPlanillaSalEdit" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="form-horizontal" id="formObservacionPlanillaSalEdit" data-toggle="validator" onsubmit="return false;"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <h4 class="modal-title" id="h4ModalObservacionPlanillaSalEdit">Observaciones sobre la Planilla Salarial</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <div class="div-observacion-planillasal-edit" id="divObservacionPlanillaSalEdit">
                        <label class="col-sm-2 control-label" for="txtObservacionPlanillaSalEdit">Observaci&oacute;n:</label>
                        <div class="col-md-10"  form-group>
                            <textarea id="txtObservacionPlanillaSalEdit" class="form-control"></textarea>
                            <span class="help-block" id="helpErrorObservacionPlanillaSalEdit"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnCerrarObservacionPlanillaSalEdit" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-compress"></i>Cerrar</button>
                <button type="button" id="btnAplicarObservacionPlanillaSalEdit" class="btn btn-primary"><i class="fa fa-thumbs-o-up"></i>Aplicar</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!--</form></div>-->
</body>
<div id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>
<style type="text/css">
    .evo-pop{z-index:1151 !important;}
</style>