<script type="text/javascript">
    $(document).ready(function () {
        $('#gestion').change(function(){
            var gestion=$(this).val();
            var organigrama_id = $("#organigrama_id").val();
            location.href = '/organigramas/personal/'+organigrama_id+'/'+gestion;
        });

    });
</script>
<div class="row">
	<div class="col-lg-12">
		<h1>Personigrama</h1>		
	</div>
</div>
<a href="/organigramas"> << Volver</a>
<div class="row">
    <div class="col-md-12" class="form-horizontal">
        <div class="form-group">
                <label class="col-lg-2 control-label">Gestíón:</label>
                <div class="col-lg-4">
                    <input type="hidden" id="organigrama_id" value="<?php echo $organigrama_id ?>">
                    <?php echo $gestiones; ?>
                </div>
            </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 animation-stretchRight">
        <div class="widget">
             <div style="width: 100%;" ><?php echo $lista;?></div>
        </div>
    </div>
</div>

<div class="row" style="position: absolute;">
    <div class="col-sm-12 animation-stretchRight">
        <div class="widget">
             <div id="chart" class="orgChart"></div>
        </div>
    </div>

</div>

  <script>
    jQuery(document).ready(function() {
        $("#org").jOrgChart({
            chartElement : '#chart',
            dragAndDrop  : true
        });

    });
    </script>