<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="gi gi-dashboard"></i>P&aacute;gina de Inicio<br><small>Bienvenid@: <?php echo $nombres; ?></small>
        </h1>
    </div>
</div>
<?php if($modalidad==1){ ?>
<div class="row" id="divDashbordAdministrador">
    <div class="col-sm-12 col-md-4 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/relaborales" class="aWidgetRelab widget-icon pull-left themed-background animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/relaborales';">
                    Plazo Indefinido: <strong><?php echo $permanentes; ?></strong><br />
                    <small>Personas</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/relaborales" class="widget-icon pull-left themed-background-amethyst  animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/relaborales';">
                    Plazo Fijo: <strong><?php echo $eventuales; ?></strong><br />
                    <small>Personas</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/relaborales" class="widget-icon pull-left themed-background-fire animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/relaborales';">
                    Consultor&iacute;a: <strong><?php echo $consultores; ?></strong><br />
                    <small>Personas</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/relaborales" class="widget-icon pull-left themed-background-night animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/relaborales';">
                    Total: <strong><?php echo $total_personal; ?></strong><br />
                    <small>Personas</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/procesoscontrataciones" class="widget-icon pull-left themed-background-spring animation-fadeIn">
                    <i class="fa fa-cogs"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/procesoscontrataciones';">
                    En Ejecuci&oacute;n: <strong><?php echo $procesos_pendientes; ?></strong><br />
                    <small>Procesos</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/procesoscontrataciones" class="widget-icon pull-left themed-background-flatie animation-fadeIn">
                    <i class="fa fa-cogs"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/procesoscontrataciones';">
                    Concluidos: <strong><?php echo $procesos_concluidos; ?></strong><br />
                    <small>Procesos</small>
                </h3>
            </div>
        </div>
    </div>
</div>
    <!--<div class="row">
        <div class="col-sm-6 animation-stretchRight">
            <div class="widget">
                <div id="divEncuestaPrimeraPregunta" style="width: 100%; height: 400px;">Encuesta</div>
                <label id="lblPregunta1">Pregunta 1: Considerando un monto aproximado de Bs 300 por persona, prefiere usted que el monto económico del Fondo Social sea destinado en esta navidad a:</label>
            </div>
        </div>
        <div class="col-sm-6 animation-stretchRight">
            <div class="widget">
                <div id="divEncuestaSegundaPregunta" style="width: 100%; height: 400px;">Encuesta</div>
                <label id="lblPregunta2">Pregunta 2: En reconocimiento a la labor desempeñada por los jóvenes estudiantes participantes del programa “Trabajo con altura” en las líneas en funcionamiento de nuestra Empresa, considera usted la posibilidad de entregar un canaston equivalente a un monto aproximado de Bs.80?</label>
            </div>
        </div>
    </div>-->

<?php } else {?>
    <div class="row" id="divDashbordConsulta">
        <div class="col-sm-6 col-lg-3">
            <div class="widget">
                <div class="widget-simple">
                    <label class="col-md-4 control-label" for="lstgestiones">Gesti&oacute;n</label>
                    <select id="lstGestion" name="lstGestion" class="form-control"></select>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3">
            <div class="widget">
                <div class="widget-simple">
                    <a href="/misrelaborales" class="widget-icon pull-left themed-background animation-fadeIn">
                        <i class="fa fa-users"></i>
                    </a>
                    <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/misrelaborales';">
                        Antigüedad Laboral <strong><?php
                            foreach($antiguedad as $ant){
                                echo "</br><small>".$ant->condiciones."</br>";
                                $fechaIng = $ant->fecha_ing != "" ? date("d-m-Y", strtotime($ant->fecha_ing)) : "";
                                $fechaUlt = $ant->fecha_ult != "" ? date("d-m-Y", strtotime($ant->fecha_ult)) : "";
                                echo "Periodo: ".$fechaIng." al ".$fechaUlt."</br>";
                                echo "Tiempo: ".$ant->antiguedad." meses"."</small>";
                            }
                            ?></strong><br/>
                    </h3>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3">
            <div class="widget">
                <div class="widget-simple">
                    <a href="/misboletasexcepciones" class="widget-icon pull-left themed-background-night animation-fadeIn">
                        <i class="fa fa-users"></i>
                    </a>
                    <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/misboletasexcepciones';">
                        Boletas registradas: <strong><?php echo $boletasExcepcionesRegistradas; ?></strong><br />
                        <small>Boletas en Elaboraci&oacute;n, Elaboradas o Enviadas</small>
                    </h3>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-lg-3">
            <div class="widget">
                <div class="widget-simple">
                    <a href="/misideas" class="widget-icon pull-left themed-background-spring animation-fadeIn">
                        <i class="fa fa-lightbulb-o"></i>
                    </a>
                    <h3 class="widget-content text-right animation-pullDown" ondblclick="location.href = '/misideas';">
                        Ideas registradas: <strong><?php echo $ideasPublicadas; ?></strong><br />
                        <small>Ideas de negocio publicadas</small>
                    </h3>
                </div>
            </div>
        </div>
    </div>
<input type="hidden" id="hdnIdPersona" value="<?php echo $id_persona; ?>">
    <div class="row">
        <div class="col-sm-12 animation-stretchRight">
            <div class="widget">
                <div id="container" style="min-width: 400px; height: 400px; margin: 0 auto"></div>
            </div>
        </div>
    </div>
<?php }?>
<input type="hidden" id="hdnModalidad" value="<?php echo $modalidad; ?>">
<input type="hidden" id="hdnGestion" value="<?php echo $gestion; ?>">