</head>
<body>
<h2 style="padding-top: 0px; width: 100%;"><b>Gesti&oacute;n de Excepciones</b></h2>
<div id='divTabExcepciones'>
<ul>
    <li id="liList">Listado</li>
    <li id="liNew">Nuevo</li>
    <li id="liEdit">Modificaci&oacute;n</li>
</ul>
<br>
<div class="row section" id="divList">
    <div class="col-md-10">
        <!-- Input Grid Block -->
        <div class="block">
            <!-- Input Grid Title -->
            <div class="block-title">
                <h2>Listado General</h2>
                <div id='divWidgetExcepciones'>
                    <div align="right">
                        <!--<button class="btn btn-sm btn-primary" type="button" id="btnExportarExcel" accesskey="i">
                            <i class="fi fi-xls"></i>
                            Exportar Excel
                        </button>
                        <button class="btn btn-sm btn-primary" type="button" id="btnExportarPDF" accesskey="i">
                            <i class="fi fi-pdf"></i>
                            Exportar PDF
                        </button>-->
                        <button class="btn btn-sm btn-primary" type="button" id="btnDesagrupartodo">
                            <i class="fa fa-chain-broken"></i>
                            Desagrupar Todo
                        </button>
                        <button class="btn btn-sm btn-primary" type="button" id="btnDesfiltrartodo">
                            <i class="gi gi-sorting"></i>
                            Desfiltrar Todo
                        </button>
                    </div>
                    <div id="divGridExcepciones"></div>
                </div>
            </div>
            <!-- END Input Grid Title -->

        </div>
        <!-- END Input Grid Block -->
    </div>
    <div class="col-md-2">
        <div class="block">
            <div class="block-title">
                <h2>Mostrar</h2>
                <br>
                <input type="checkbox" id="chkAllCols"> Todas / Ninguna
            </div>
            <div id="listBoxExcepciones"></div>
        </div>
    </div>
</div>
<div class="section" id="divNew">
        <h6><b>NOTA: </b>Los datos precedidos de asterisco son requerido de manera obligatoria (*).</h6>
        <div class="form-horizontal col-sm-12">
            <fieldset>
                <legend><i class="fa fa-angle-right"></i> Datos de Identificaci&oacute;n</legend>
            <div class="row">
                <div class="col-xs-6" id="divExcepcionNew">
                    <label class="col-sm-6 control-label" for="txtExcepcionNew">Excepci&oacute;n *:</label>
                    <div class="col-sm-6">
                        <textarea id="txtExcepcionNew" class="form-control" placeholder="Excepci&oacute;n.."></textarea>
                        <span class="help-block" id="helpErrorExcepcionNew"></span>
                    </div>
                </div>
                <div class="col-xs-6" id="divTipoExcepcionNew">
                    <label class="col-sm-3 control-label" for="lstTipoExcepcionNew">Tipo *:</label>
                    <div class="col-sm-6" form-group>
                        <select id="lstTipoExcepcionNew" class="form-control"></select>
                        <span class="help-block" id="helpErrorTipoExcepcionNew"></span>
                    </div>
                </div>
            </div>
                <div class="row">
                    <div class="col-xs-6" id="divCodigoNew">
                        <label class="col-sm-6 control-label" for="txtCodigoNew">C&oacute;digo *:</label>
                        <div class="col-sm-6">
                            <input type="text" id="txtCodigoNew" name="txtCodigoNew" class="form-control" placeholder="C&oacute;digo..">
                            <span class="help-block" id="helpErrorCodigoNew"></span>
                        </div>
                    </div>
                    <div class="col-xs-6" id="divColorNew">
                        <label class="col-sm-3 control-label" for="txtColorNew">Color *:</label>
                        <div class="col-sm-6">
                            <input type="text" id="txtColorNew" name="txtColorNew" class="kolorPicker form-control" value="#FFFFFF" placeholder="#FFFFFF">
                            <span class="help-block" id="helpErrorColorNew"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-4" id="divDescuentoNew">
                        <label class="col-sm-6 control-label" for="chkDescuentoNew">¿Aplicar descuento? *:</label>
                        <div class="col-sm-6">
                            <input type="checkbox" name="chkDescuentoNew" id="chkDescuentoNew" data-on-text="SI" data-off-text="NO">
                            <span class="help-block" id="helpErrorDescuentoNew"></span>
                        </div>
                    </div>
                    <div class="col-xs-4" id="divCompensatoriaNew">
                        <label class="col-sm-6 control-label" for="chkCompensatoriaNew">¿Debe compensar horas? *:</label>
                        <div class="col-sm-6">
                            <input type="checkbox" name="chkCompensatoriaNew" id="chkCompensatoriaNew" data-on-text="SI" data-off-text="NO">
                            <span class="help-block" id="helpErrorCompensatoriaNew"></span>
                        </div>
                    </div>
                    <div class="col-xs-4" id="divGeneroNew">
                        <label class="col-sm-6 control-label" for="lstGeneroNew">G&eacute;nero *:</label>
                        <div class="col-sm-6">
                            <select id="lstGeneroNew" class="form-control"><option value="">Seleccionar...</option></select>
                            <span class="help-block" id="helpErrorGeneroNew"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-4" id="divHorarioNew">
                        <label class="col-sm-6 control-label" for="chkHorarioNew">¿Solicitar Horario? *:</label>
                        <div class="col-sm-6">
                            <input type="checkbox" name="chkHorarioNew" id="chkHorarioNew" data-on-text="SI" data-off-text="NO">
                            <span class="help-block" id="helpErrorHorarioNew"></span>
                        </div>
                    </div>
                    <div class="col-xs-4" id="divRefrigerioNew">
                        <label class="col-sm-6 control-label" for="chkRefrigerioNew">¿Pagar Refrigerio? *:</label>
                        <div class="col-sm-6">
                            <input type="checkbox" name="chkRefrigerioNew" id="chkRefrigerioNew" data-on-text="SI" data-off-text="NO">
                            <span class="help-block" id="helpErrorRefrigerioNew"></span>
                        </div>
                    </div>
                    <div class="col-xs-4" id="divBoletaNew">
                        <label class="col-sm-6 control-label" for="chkBoletaNew">¿Con Boleta? *:</label>
                        <div class="col-sm-6">
                            <input type="checkbox" name="chkBoletaNew" id="chkBoletaNew" data-on-text="SI" data-off-text="NO">
                            <span class="help-block" id="helpErrorBoletaNew"></span>
                        </div>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend><i class="fa fa-angle-right"></i> Frecuencia:</legend>
                <div class="form-group" id="divFrecuenciaNew">
                    <div class="col-sm-3" id="divCantidadNew">
                        Cantidad:
                        <input type="text" name="txtCantidadNew" id="txtCantidadNew" class="form-control decimal">
                        <span class="help-block" id="helpErrorCantidadNew"></span>
                    </div>
                    <div class="col-sm-3" id="divUnidadNew">
                        Unidad:
                        <select id="lstUnidadNew" name="lstUnidadNew" class="form-control"><option value="">Seleccionar...</option></select>
                        <span class="help-block" id="helpErrorUnidadNew"></span>
                    </div>
                    <div class="col-sm-3" id="divFraccionamientoNew">
                        Fraccionamiento:
                        <select id="lstFraccionamientoNew" name="lstFraccionamientoNew" class="form-control" disabled><option value="" dataid-unidad="0">Seleccionar...</option></select>
                        <span class="help-block" id="helpErrorFraccionamientoNew"></span>
                    </div>
                    <div class="col-sm-3" id="divFrecuenciaNew">
                        Resultado:
                        <span id="spanFrecuenciaNew" class="form-control"></span>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend><i class="fa fa-angle-right"></i> &nbsp;</legend>
                <div class="form-group div-excepciones" id="divObservacionNew">
                    <label class="col-md-3 control-label" for="txtObservacionNew">Observaciones:</label>
                    <div class="col-md-6">
                        <textarea id="txtObservacionNew" name="txtObservacionNew" class="form-control" placeholder="Observaciones.."></textarea>
                    </div>
                    <span class="help-block" id="helpErrorObservacionNew"></span>
                </div>
        </fieldset>
        <div class="form-group form-actions">
            <div class="col-md-8 col-md-offset-4">
                <button id="btnGuardarExcepcionNew" class="btn btn-sm btn-primary" type="button">
                    <i class="fa fa-floppy-o"></i>
                    Guardar
                </button>
                <button id="btnCancelarExcepcionNew" class="btn btn-sm btn-warning" type="button">
                    <i class="fa fa-repeat"></i>
                    Cancelar
                </button>
            </div>
        </div>
        </div>
</div>
<div class="section" id="divEdit">
    <h6><b>NOTA: </b>Los datos precedidos de asterisco son requerido de manera obligatoria (*).</h6>
    <div class="form-horizontal col-sm-12">
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> Datos de Identificaci&oacute;n</legend>
            <div class="row">
                <div class="col-xs-6" id="divExcepcionEdit">
                    <label class="col-sm-6 control-label" for="txtExcepcionEdit">Excepci&oacute;n *:</label>
                    <div class="col-sm-6">
                        <textarea id="txtExcepcionEdit" class="form-control" placeholder="Excepci&oacute;n.."></textarea>
                        <span class="help-block" id="helpErrorExcepcionEdit"></span>
                    </div>
                </div>
                <div class="col-xs-6" id="divTipoExcepcionEdit">
                    <label class="col-sm-3 control-label" for="lstTipoExcepcionEdit">Tipo *:</label>
                    <div class="col-sm-6" form-group>
                        <select id="lstTipoExcepcionEdit" class="form-control"></select>
                        <span class="help-block" id="helpErrorTipoExcepcionEdit"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6" id="divCodigoEdit">
                    <label class="col-sm-6 control-label" for="txtCodigoEdit">C&oacute;digo *:</label>
                    <div class="col-sm-6">
                        <input type="text" id="txtCodigoEdit" name="txtCodigoEdit" class="form-control" placeholder="C&oacute;digo..">
                        <span class="help-block" id="helpErrorCodigoEdit"></span>
                    </div>
                </div>
                <div class="col-xs-6" id="divColorEdit">
                    <label class="col-sm-3 control-label" for="txtColorEdit">Color *:</label>
                    <div class="col-sm-6">
                        <input type="text" id="txtColorEdit" name="txtColorEdit" class="kolorPicker form-control" value="#FFFFFF" placeholder="#FFFFFF">
                        <span class="help-block" id="helpErrorColorEdit"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4" id="divDescuentoEdit">
                    <label class="col-sm-6 control-label" for="chkDescuentoEdit">¿Aplicar descuento? *:</label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="chkDescuentoEdit" id="chkDescuentoEdit" data-on-text="SI" data-off-text="NO">
                        <span class="help-block" id="helpErrorDescuentoEdit"></span>
                    </div>
                </div>
                <div class="col-xs-4" id="divCompensatoriaEdit">
                    <label class="col-sm-6 control-label" for="chkCompensatoriaEdit">¿Debe compensar horas? *:</label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="chkCompensatoriaEdit" id="chkCompensatoriaEdit" data-on-text="SI" data-off-text="NO">
                        <span class="help-block" id="helpErrorCompensatoriaEdit"></span>
                    </div>
                </div>
                <div class="col-xs-4" id="divGeneroEdit">
                    <label class="col-sm-6 control-label" for="lstGeneroEdit">G&eacute;nero *:</label>
                    <div class="col-sm-6">
                        <select id="lstGeneroEdit" class="form-control"><option value="">Seleccionar...</option></select>
                        <span class="help-block" id="helpErrorGeneroEdit"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4" id="divHorarioEdit">
                    <label class="col-sm-6 control-label" for="chkHorarioEdit">¿Solicitar Horario? *:</label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="chkHorarioEdit" id="chkHorarioEdit" data-on-text="SI" data-off-text="NO">
                        <span class="help-block" id="helpErrorHorarioEdit"></span>
                    </div>
                </div>
                <div class="col-xs-4" id="divRefrigerioEdit">
                    <label class="col-sm-6 control-label" for="chkRefrigerioEdit">¿Pagar Refrigerio? *:</label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="chkRefrigerioEdit" id="chkRefrigerioEdit" data-on-text="SI" data-off-text="NO">
                        <span class="help-block" id="helpErrorRefrigerioEdit"></span>
                    </div>
                </div>
                <div class="col-xs-4" id="divBoletaEdit">
                    <label class="col-sm-6 control-label" for="chkBoletaEdit">¿Con Boleta? *:</label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="chkBoletaEdit" id="chkBoletaEdit" data-on-text="SI" data-off-text="NO">
                        <span class="help-block" id="helpErrorBoletaEdit"></span>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> Frecuencia:</legend>
            <div class="form-group" id="divFrecuenciaEdit">
                <div class="col-sm-3" id="divCantidadEdit">
                    Cantidad:
                    <input type="text" name="txtCantidadEdit" id="txtCantidadEdit" class="form-control decimal">
                    <span class="help-block" id="helpErrorCantidadEdit"></span>
                </div>
                <div class="col-sm-3" id="divUnidadEdit">
                    Unidad:
                    <select id="lstUnidadEdit" name="lstUnidadEdit" class="form-control"><option value="">Seleccionar...</option></select>
                    <span class="help-block" id="helpErrorUnidadEdit"></span>
                </div>
                <div class="col-sm-3" id="divFraccionamientoEdit">
                    Fraccionamiento:
                    <select id="lstFraccionamientoEdit" name="lstFraccionamientoEdit" class="form-control" disabled><option value="" dataid-unidad="0">Seleccionar...</option></select>
                    <span class="help-block" id="helpErrorFraccionamientoEdit"></span>
                </div>
                <div class="col-sm-3" id="divFrecuenciaEdit">
                    Resultado:
                    <span id="spanFrecuenciaEdit" class="form-control"></span>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend><i class="fa fa-angle-right"></i> &nbsp;</legend>
            <div class="form-group div-excepciones" id="divObservacionEdit">
                <label class="col-md-3 control-label" for="txtObservacionEdit">Observaciones:</label>
                <div class="col-md-6">
                    <textarea id="txtObservacionEdit" name="txtObservacionEdit" class="form-control" placeholder="Observaciones.."></textarea>
                </div>
                <span class="help-block" id="helpErrorObservacionEdit"></span>
            </div>
        </fieldset>
        <div class="form-group form-actions">
            <div class="col-md-8 col-md-offset-4">
                <button id="btnGuardarExcepcionEdit" class="btn btn-sm btn-primary" type="button">
                    <i class="fa fa-floppy-o"></i>
                    Guardar
                </button>
                <button id="btnCancelarExcepcionEdit" class="btn btn-sm btn-warning" type="button">
                    <i class="fa fa-repeat"></i>
                    Cancelar
                </button>
            </div>
        </div>
        <input type="hidden" id="hdnIdExcepcionEdit" value="0">
    </div>
</div>
</div>
<!--</form></div>-->
</body>
<div id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>
<style type="text/css">
    .evo-pop{z-index:1151 !important;}
</style>