<script type="text/javascript">
$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
				{ name: 'id',type: 'number'},
				{ name: 'tipo_resolucion',type: 'string'},
				//{ name: 'numero_res',type: 'number'},
				{ name: 'fecha_emi',type:'date',format: 'dd-MM-yyyy'},
				{ name: 'fecha_apr',type:'date'},
				{ name: 'activo',type:'number'},
				{ name: 'uso_string',type:'string'},
				{ name: 'uso',type:'number'}
			],
			url: '/resoluciones/list',
			cache: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar();	
		function cargar(){
			$("#jqxgrid").jqxGrid(
			{
				width: '100%',
				source: dataAdapter,
				sortable: true,
				altRows: true,
				pageable: true,
				pagerMode: 'advanced',
				showfilterrow: true,
				filterable: true,
				columns: [
				{
					text: '#', sortable: false, filterable: false, editable: false,
					groupable: false, draggable: false, resizable: false,
					datafield: '', columntype: 'number', width: '5%',
					cellsrenderer: function (row, column, value) {
						return "<div style='margin:4px;'>" + (value + 1) + "</div>";
					}
				},
				{ text: 'Nro', datafield: 'id',filtertype: 'number', width: '5%',hidden:true},
				{ text: 'Resolucion', datafield: 'tipo_resolucion', filtertype: 'input',width: '55%' },
				//{ text: 'Nro Resolucion', datafield: 'numero_res',filtertype: 'input', width: '10%' },
				{ text: 'Fecha Emision', datafield: 'fecha_emi', filtertype: 'range', width: '10%', cellsalign: 'center', cellsformat: 'dd-MM-yyyy',align:'center'},
				{ text: 'Fecha Aprobación', datafield: 'fecha_apr', filtertype: 'range', width: '10%', cellsalign: 'center', cellsformat: 'dd-MM-yyyy',align:'center'},
				{ text: 'Uso Especifico', datafield: 'uso_string',filtertype: 'input', width: '20%' },
				]
			});

}
            // update the edited row when the user clicks the 'Save' button.
            $("#jqxgrid").bind('rowselect', function (event) {
            	var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', event.args.rowindex);
            	$("#id").val(dataRecord.id);
            	$("#tipo_resolucion").val(dataRecord.tipo_resolucion);
                //$("#numero_res").val(dataRecord.numero_res);
                $("#uso").val(dataRecord.uso);
                $("#activo").val(dataRecord.activo);
                if (dataRecord.uso==1) {$("#activo_id").show();
            	}else{
            		$("#activo_id").hide();
            	}

                var fe = $.jqx.dataFormat.formatdate(dataRecord.fecha_emi, 'dd-MM-yyyy');
                var fa = $.jqx.dataFormat.formatdate(dataRecord.fecha_apr, 'dd-MM-yyyy');
                $("#fecha_emi").val(fe);
                $("#fecha_apr").val(fa);
            });

            $("#add").click(function(){
            	$("#titulo").text("Adicionar");
            	$("#id").val("");
            	$("#tipo_resolucion").val("");
            	//$("#numero_res").val("");
            	$("#uso").val('0');
                $("#activo").val('0');
            	$("#fecha_emi").val("");
            	$("#fecha_apr").val("");
            	$('#myModal').modal('show');
            	$("#activo_id").hide();
            });

            $("#edit").click(function(){
            	if($("#id").val()!=""){
            		$("#titulo").text("Editar");
            		$('#myModal').modal('show');        		
            	}else{
            		bootbox.alert("<strong>¡Mensaje!</strong> Seleccionar un registro para editar.");
            	}
            });

            $("#delete").click(function(){
            	if($("#id").val()!=""){
            		bootbox.confirm("<strong>¡Mensaje!</strong> Esta seguro de eliminar el registro.", function(result) {
            			if (result==true) {
            				var v=$.ajax({
            					url:'/resoluciones/delete/',
            					type:'POST',
            					datatype: 'json',
            					data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
            			}
            		});
            	}else{
            		bootbox.alert("<strong>¡Mensaje!</strong> Seleccionar un registro para eliminar.");
            	}
            });

            $("#uso").change(function(){
            	if($("#uso").val()==1){
            		$("#activo_id").show();
            	}else{
            		$("#activo_id").hide();
            	}
            });

$('#testForm').validate({
	rules: {
		fecha_apr: {
			required: true
		},
		fecha_emi: {
			required: true
		},
		tipo_resolucion: {
			required: true
		}
		// ,
		// numero_res: {
		// 	required: true
		// }
	},
	highlight: function (element) {
		$(element).closest('.control-group').removeClass('success').addClass('error');
	},
	success: function (element) {
        //element.text('OK!').addClass('valid').closest('.control-group').removeClass('error').addClass('success');
        element.addClass('valid').closest('.control-group').removeClass('error').addClass('success');
    },
    submitHandler: function (form) {
            // form validates so do the ajax
            var fecha_apr = $('#fecha_apr').val();
            var fecha_emi = $('#fecha_emi').val();
            var v=$.ajax({
            	url:'/resoluciones/save/',
            	type:'POST',
            	datatype: 'json',
            	data:{id:$("#id").val(),tipo_resolucion:$("#tipo_resolucion").val(),uso:$("#uso").val(),activo:$("#activo").val(),fecha_apr:fecha_apr,fecha_emi:fecha_emi},
						success: function(data) { cargar(); //alert(data); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
            $('#myModal').modal('hide');
            return false; // ajax used, block the normal submit
        }
    });		
            
	});
</script>

<div class="row">
	<div class="col-lg-12">
		<h1>Resoluciones</h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div class="form-group form-actions">
					<div class="col-xs-12">
						<button class="btn btn-sm btn-primary" type="button" id="add"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
						<button class="btn btn-sm btn-warning" type="button" id="edit"><i class="fa fa-pencil fa-fw"></i> Editar</button>
						<button class="btn btn-sm btn-danger" type="button" id="delete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>
			</div>
		</div>
		
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm" data-toggle="validator"/>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo">Editar</h4>
			</div>
			<div class="modal-body">
				<input id="id" name="id" type="hidden" />
				<div class="form-group">
					<label class="col-md-3 control-label">Resolución</label>
					<div class="col-md-9">
						<input id="tipo_resolucion" name="tipo_resolucion" type="text" class="form-control"/>
					</div>
				</div>
				<!-- <div class="form-group">
					<label class="col-md-3 control-label">Numero Resolución</label>
					<div class="col-md-9">
						<input id="numero_res" name="numero_res" type="text" class="form-control"/>
					</div>
				</div> -->
				<div class="form-group">
					<label class="col-md-3 control-label">Fecha Emisión</label>
					<div class="col-md-9">
						<input type="text" id="fecha_emi" name="fecha_emi"  class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Fecha Aprobación</label>
					<div class="col-md-9">
						<input type="text" id="fecha_apr" name="fecha_apr" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Uso</label>
					<div class="col-md-9">
						<?php echo $uso ?>
					</div>
				</div>
				<div class="form-group" id="activo_id">
					<label class="col-md-3 control-label">Activo</label>
					<div class="col-md-9">
						<?php echo $activo ?>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->

<style type="text/css">
	.datepicker{
		z-index:1151 !important;
	}
</style>

