<?php
if (isset($_POST['username'])) {
    $user = $_POST['username'];
} else {
    $user = '';
}
?>
<!-- BEGIN ERROR BOX -->
<?php echo $this->flashSession->output(); ?>
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/css/plugins.css">
<link rel="stylesheet" href="/assets/css/main.css">
<link rel="stylesheet" href="/assets/css/themes.css">
<script src="/assets/js/vendor/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="/js/jqwidgets/scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/js/login/oasis.password.js"></script>

<div class="alert alert-success" id="divPasswordSuccess">
    <button type="button" class="close" aria-hidden="true">×</button>
    <h4><i class="fa fa-check-circle"></i> &Eacute;xito</h4>
    <span class="span-alert" id="spanSuccess"></span>
</div>
<div class="alert alert-info" id="divPasswordInfo">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4><i class="fa fa-info-circle"></i> Importante!</h4>
    <span class="span-alert" id="spanInfo"></span>
</div>
<div class="alert alert-warning" id="divPasswordWarning">
    <button type="button" class="close" aria-hidden="true">×</button>
    <h4><i class="fa fa-exclamation-circle"></i> Alerta!</h4>
    <span class="span-alert" id="spanWarning"></span>
</div>
<div class="alert alert-danger" id="divPasswordDanger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4><i class="fa fa-times-circle"></i> Error!</h4>
    <span class="span-alert" id="spanDanger"></span>
</div>
<!-- END ERROR BOX -->
<form action="#" method="post" onsubmit="return false;">
    <p>Ingrese su direcci&oacute;n de correo electr&oacute;nico institucional y le enviaremos un enlace para restablecer la contrase&ntilde;a a su Bandeja de Entrada.</p>
    <input id="email" type="email" placeholder="Email" name="email" class="input-field" required/>
    <button id="btnEnviarEmail" type="submit" class="btn btn-login btn-reset">Enviar</button>
</form>
<div class="login-links">
    <a href="/login">Ya tienes cuenta  <strong>Ingresar</strong></a>
</div>
<div id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>